### ISSUE TITLE
Add the app to Homebrew/Cask

### ISSUE THREAD

**Issue by ephimoff** [milgra/highsierramediakeyenabler#11]
Thanks for the awesome app. You are the true MVP!
Are you planning to add your app to the Cask maybe? It would be great. This will allow to automate/provision new setups.

**Comment by chrishiste** [comment]
+1

**Comment by milgra** [comment]
Hi, Thank you! I will check how difficult it is to maintain a cask.

**Comment by allejo** [comment]
@milgra it's not difficult at all, see [their docs](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md). If you go with the "unversioned download" for this, you shouldn't need to update the Cask definition ever unless the download URL changes. If you opt for having a versioned download, you'll have to submit a PR to their repo each time you release a new version.

**Comment by alejandroivan** [comment]
Looks like this is already added to Caskroom.
Doing a `brew cask install highsierramediakeyenabler` will install the app without issues.

**Comment by milgra** [comment]
That's super cool news! :)

**Comment by stonerl** [comment]
Could you provide a versioned download link for the latest versions?

The current Version is 1.9 but the link is:
http://milgra.com/downloads/HighSierraMediaKeyEnabler.zip

It would be better for homebrew if you would provide every version with an absolute link:

http://milgra.com/downloads/HighSierraMediaKeyEnabler1.9.zip

Like you do with the older version

**Comment by Triloworld** [comment]
It's working fine @stonerl. Version 1.9 build 4 checked moment ago :)

**Comment by stonerl** [comment]
@Triloworld I know that the current cask is working. But it would be preferable if the cask was versioned. That's why I'm asking for versioned links for the latest version.

**Comment by Triloworld** [comment]
Ok. Just do new Issue :) This one is close. Brew cask get newest version. If need to be more then why not, I'am sure it will be added, you can add that as pull request <3

**Comment by alejandroivan** [comment]
The problem with unversioned links is that `brew cask upgrade highsierramediakeyenabler` doesn't work. The way to upgrade is to uninstall and reinstall with `brew cask reinstall highsierramediakeyenabler`.
Unversioned casks are for software that update by itself (like Spotify/VLC/Sketch/others do).

**Comment by stonerl** [comment]
i just opened a new issue #45

**Comment by stonerl** [comment]
@alejandroivan 

Not exactly. unversioned  casks are only used when no versioned download is available (hence sha256 is not available due to changing checksums). Software that updates itself, e.g. VLC, still has versioned casks, but uses the `auto_updates true`stanza.
