### ISSUE TITLE
Did you try this?

### ISSUE THREAD

**Issue by kud** [milgra/highsierramediakeyenabler#12]
on Sierra, you had to disable the agent which is responsable for media keys to stop using itunes and being able to use Spotify via:

`$ launchctl unload -w /System/Library/LaunchAgents/com.apple.rcd.plist 2> /dev/null`

However, on High Sierra, it's quite the opposite. If you want to make it work with Spotify or whatever, you have to load it

`$ launchctl load -w /System/Library/LaunchAgents/com.apple.rcd.plist 2> /dev/null`

It works to me, no more need to use your app.

**Comment by milgra** [comment]
Hi, thanks for the tip but it still works pretty chaotically for me if I run iTunes, Spotify and Safari at the same time. I guess when only one is running it works well. With the app now you can select iTunes or Spotify explicitly.

**Comment by kud** [comment]
True say! I was today in this case where Firefox was to the top of list and I was unable to change Spotify so yeah I will consider again your app I think. :)
