### ISSUE TITLE
doesn't work with Airpod

### ISSUE THREAD

**Issue by quangvh23** [milgra/highsierramediakeyenabler#16]
Take out 1 piece of Airpod doesn't stop the music despite "Automatic Ear Detection" enabled.
Take out both pieces of Airpod make the Mac use the speaker, which is really annoying.

**Comment by alejandroivan** [comment]
As stated in the repo description, this app works with physical buttons. No Touch Bar or Airpods are supported (but if you can add that functionality, I would assume you can pull request your updates).

**Comment by joaodforce** [comment]
Duplicate of #19

**Comment by milgra** [comment]
This is a behaviour of MacOS I cannot change :(
