### ISSUE TITLE
Holding next / previous skips songs

### ISSUE THREAD

**Issue by Dalibor22x** [milgra/highsierramediakeyenabler#2]
Holding next / previous button skips songs instead of fast forward / rewind.

**Comment by Gohstgamer** [comment]
I have the same issue as @Dalibor22x 
Default configuration should be:
pressing long --> forward/rewind
pressing short --> skip

**Comment by ldexterldesign** [comment]
+1

**Comment by GTSven** [comment]
+1

Keep up the good work!

**Comment by milgra** [comment]
I will see what can I do about this.

**Comment by sh1217sh** [comment]
@milgra
Please review PR #18.

**Comment by milgra** [comment]
PR merged, fast forward/rewind is working with iTunes, thank you!
