### ISSUE TITLE
[Feature Request] Pausing the service

### ISSUE THREAD

**Issue by Daniol71** [milgra/highsierramediakeyenabler#20]
It would be nice to be able to pause the service from the notifications bar without having to quit the app. Let's say if you wanted to quickly switch back to High Sierra's default handling of Play/Pause for any reason.

**Comment by maciboy** [comment]
It would be great if this pause feature would kick in automatically if neither iTunes nor Spotify is running

**Comment by maciboy** [comment]
@Daniol71 
If you like you can test the option I added and give feedback:
https://github.com/maciboy/highsierramediakeyenabler/releases/tag/v1.7-b2

**Comment by milgra** [comment]
Pause is added, thank you!
