### ISSUE TITLE
[Feature Request] Use default behavior (e. g.  pause Safari video) when iTunes & Spotify are not running

### ISSUE THREAD

**Issue by maciboy** [milgra/highsierramediakeyenabler#21]
Would it be possible to implement a check if Spotify and/or iTunes is running and commands should be forwarded.
If both are not running it would be cool if macOS’s standard behavior could be used and the command is directed to the current app in foreground.

However, thanks a lot for this great app, Apples change is not appreciated by me either….

**Comment by alejandroivan** [comment]
This is similar to #20 

If you want the default behavior, you just need to close the app from the menu bar and that's it.
Anyway, this is a really lightweight app, so re-opening it won't take much time (a couple of seconds at most).

**Comment by maciboy** [comment]
However, this „pause“ should happen automatically if the app recognizes that Spotify/iTunes Are not running

**Comment by sh1217sh** [comment]
The purpose of this app is to bring back the behavior of media keys from previous versions of macOS. When iTunes is not running, the app will try to open iTunes (this was the original behavior of play/pause key).
I think bypassing this app with certain key combination can be a compromise.

**Comment by maciboy** [comment]
I created a fork, where I implemented the check as described above.
https://github.com/maciboy/highsierramediakeyenabler/commit/c003f70c05b08ed85af4870539599fbb1f305183#diff-5a6bd51f3187dcf5ed930628e4ed1a4e
If a media key is pressed and neither Spotify nor iTunes are running, then the event is forwarded to the media application that is currently active (instead of starting iTunes or Spotify).

**Comment by milgra** [comment]
feature is added, thank you!
