### ISSUE TITLE
Weird behaviour when Spotify and iTunes both open

### ISSUE THREAD

**Issue by dunnkers** [milgra/highsierramediakeyenabler#3]
First of all, thanks for this neat tool to fix the undesired behaviour of the media keys caused by Safari 11 / MacOS High Sierra! Now, I bumped into a little problem.

When Spotify and iTunes are **both** open, pressing play/pause actually just turns of either one of them and turns on the other one. Would be nice if this was fixed. Otherwise great tool ✌🏻.

**Comment by alejandroivan** [comment]
#14 should handle this.

**Comment by dunnkers** [comment]
Great, thanks! That should do it.

**Comment by milgra** [comment]
Check out the latest version.

**Comment by dunnkers** [comment]
Will check out 1.5, thanks.
