### ISSUE TITLE
Volume control?

### ISSUE THREAD

**Issue by pooley999** [milgra/highsierramediakeyenabler#32]
I understand this wasn't designed with volume control in mind, but I remember years ago I used an old tool called "iTunes volume controller" (Copyright © 2012 Andrea Alberti.) This tool gave the option to use a modifier key to send the volume control to the items application " ⌘ + Volume up" I think this would be a fabulous addition to a your excellent tool.

**Comment by alejandroivan** [comment]
But there's already a volume control embedded into your Mac keyboard. You can also enable graphical volume control in System Preferences. There are other tools, like BetterTouchTool that you can configure to do these specific tasks.

**Comment by pooley999** [comment]
It would just be a nice feature. The functionally of that app was clever. Say you were watching a youtube video but the music coming out of you Amazon echo was a little too loud, but you didn't want it off, You just held ⌘ and tapped volume down to effect Spotify volume rather than system audio. The main volume up and down keys remained dedicated to the system audio, so release ⌘ and tap tap volume up on system. 

Its a brilliant application though. I certainly couldn't do it. It would just be a cool feature.

"below is that dog old application I used to use."
<img width="209" alt="screen shot 2018-02-27 at 15 29 30" src="https://user-images.githubusercontent.com/24643335/36737492-134d5ee0-1bd3-11e8-88f3-0c81e471fa45.png">
[iTunes Volume Control.dmg.zip](https://github.com/milgra/highsierramediakeyenabler/files/1763500/iTunes.Volume.Control.dmg.zip)

**Comment by milgra** [comment]
It would make the app too complicated, sorry :(
