### ISSUE TITLE
Pause feature doesn't work correctly.

### ISSUE THREAD

**Issue by arvind-balaji** [milgra/highsierramediakeyenabler#36]
The pause feature seems to disable media keys completely rather than returning to normal functionality (controlling the active window).
For example, Youtube open with Spotify in background - Without the program, the media keys control the active window which is youtube (default High Sierra behavior). With the program started and Spotify prioritized, the media keys control Spotify. But when I enable the pause feature, the media keys control neither Spotify or Youtube.

**Comment by milgra** [comment]
It's true, I will investigate, thank you!
