### ISSUE TITLE
Request: Allow certain sources

### ISSUE THREAD

**Issue by clausbertels** [milgra/highsierramediakeyenabler#37]
Hey guys, wonderful little app that I wish was built-in, but alas! 

I sometimes use soundcloud and mixcloud.com to play music. I was wondering if you guys could build a sort of whitelist feature to detect what domain the media is playing from. That way I can still use the media keys for the music I stream via my browser. Tbh, it's quite a complicated interface problem to solve. 

Anyway, just wondering, let me know!

Respect and love
Claus

**Comment by milgra** [comment]
Hi, sorry but for every application I have to generate and add a header file and it makes things complicated. For now I stick with Spotify and iTunes, the perfect app for you is [Beardedspice](http://beardedspice.github.io)
