### ISSUE TITLE
Notification center "Now Playing" widget

### ISSUE THREAD

**Issue by CharlineCouchot** [milgra/highsierramediakeyenabler#38]
Hi there.

First off, thank you for your work. 
I noticed a slight inconvenience with the app : it takes over the notification center widget "Now Playing" making it useless in terms of seeing the title of the track being played. Is there anyway you can still take over the control of media keys and still display info about the track in the widget ? 
![screen shot 2018-03-20 at 11 01 29](https://user-images.githubusercontent.com/6357763/37662735-1428dd6a-2c2e-11e8-9f62-114556b7b4a9.png)

Best

**Comment by sh1217sh** [comment]
This is intended to prevent other players get button press from headphones and mess up the playback. (Which is not working as we expected and we are looking for a solution for this).
For now, you can use the older version (1.7).

**Comment by CharlineCouchot** [comment]
I see. Well I don't use my headphones' buttons so I should be fine with 1.7. Thank you !
