### ISSUE TITLE
Play/pause state does not update on the Touch Bar

### ISSUE THREAD

**Issue by dnicolson** [milgra/highsierramediakeyenabler#39]
The functionality works with the Touch Bar, the state does not change though. If the state was playing when opening HighSierraMediaKeyEnabler it will stay that way and the same if the state was paused.

**Comment by dnicolson** [comment]
The problem is resolved after updating to macOS 10.13.4 from 10.13.3.

**Comment by dnicolson** [comment]
It turns out restarting is what resolved the issue. I'm not sure how to exactly reproduce the issue yet.

MacBook Pro (15-inch, 2016) with Touch Bar.
macOS 10.13.4 (17E199).

**Comment by milgra** [comment]
Another problem that didn't exist before the Touch Bar :( I will investigate, thanks!

**Comment by milgra** [comment]
Is it still a problem? I don't have a touchbar macbook any more :(

**Comment by dnicolson** [comment]
I don't have one anymore either.

**Comment by milgra** [comment]
okay, thanks!

**Comment by dnicolson** [comment]
The issue still exists on macOS 10.14.4 (18E226).
