### ISSUE TITLE
Allowing third-party kernel extensions not possible while HighSierraMediaKeyEnabler is running

### ISSUE THREAD

**Issue by walkintom** [milgra/highsierramediakeyenabler#42]
Probably a bit of a niche issue but I found today on High Sierra 10.13.4, a third-party kernel extension would not load via the Allow button in System Preferences -> Security & Privacy while HighSierraMediaKeyEnabler was running. Quitting the app then allowed the extension to be loaded via the Allow button.

**Comment by dfmuir** [comment]
I've experienced this issue as well. It took me a while to understand this was the cause. Apple prevents you from pushing the allow button on 3rd Party extensions when apps are controlling the mouse or keyboard. This is a security feature to prevent apps from being able to highjack the input to press the allow button and enable themselves.

To recreate:

1) Begin installing the program "Little Snitch"
2) When the installer prompts you to go into the System Preferences to allow it, press the Allow button and see no result.
3) Quit the installer and Quit High Sierra Media Key Enabler
4) Re-run the installer and see that the above process works.

Hope this helps. This is a real problem. Let me know if you have questions.

**Comment by milgra** [comment]
It seems that I can't do much about this issue, I cannot detect if an installer wants event tapping and diable the app temporarily :( The best I can do is to add a warning about this in the readme. Thank you anyways.

**Comment by alejandroivan** [comment]
@milgra this just happened to me yesterday. It's probably a candidate for showing this as a "known issue" on the main page, since basically any installation of system extensions will need to close MMKF to allow them to run.
