### ISSUE TITLE
Can't change Safari Search Engine when HighSierra Media Key Enabler is running

### ISSUE THREAD

**Issue by Candide19215** [milgra/highsierramediakeyenabler#43]
When HighSierra Media Key Enabler is opened and I go to Safari > Preferences > Search and try to change the Search Engine it automatically switches back to the old Search Engine. For example when Google is selected as the Search Engine, it will stay on Google even if I try to select another Search Engine, e.g. Bing. This problem doesn't occur when HighSierra Media Key Enabler is closed.

**Comment by aonez** [comment]
Also once MediaKeyEnabler is closed, the Safari Preferences should be reopened.

**Comment by aonez** [comment]
Possbily this is the same issue as #42 and the fix (if any) will work for booth.

**Comment by aonez** [comment]
With https://github.com/milgra/highsierramediakeyenabler/pull/47/commits/a9881feb62ee1f10baf9b6b038105945c69ec75a just pausing works, no need to quit.

**Comment by milgra** [comment]
Well, that is some strange issue! It seems Safari preferences uses some weird key event catching. Since pausing HSMKE is a good workaround I'm not planning to investigate this because it looks like a minor issue, but thank you for the catch!
