### ISSUE TITLE
Feature request: Display play status in menu icon

### ISSUE THREAD

**Issue by gklka** [milgra/highsierramediakeyenabler#44]
If it already has a menu icon, make it useful: display if something is playing or not in the menu.

**Comment by Hum4n01d** [comment]
I use [SpotMenu ](https://github.com/kmikiy/SpotMenu) for this

**Comment by milgra** [comment]
Good idea, but It's just a key press forwarder, I don't want to extend it that much. I planned to add prev/next/play menu bar buttons also but that should be a separate app. SpotMenu looks good for this.
