### ISSUE TITLE
Versioned download link for all releases

### ISSUE THREAD

**Issue by stonerl** [milgra/highsierramediakeyenabler#45]
Could you provide a versioned download link for the latest versions?

The current Version is 1.9, but the link is:
http://milgra.com/downloads/HighSierraMediaKeyEnabler.zip

instead of
http://milgra.com/downloads/HighSierraMediaKeyEnabler1.9.zip

It would be better for homebrew if you could provide every release with an absolute link, as you do with the older versions.

**Comment by milgra** [comment]
Sure, I will do that from now on since I created a brand new shiny browsable download folder for all versions [http://www.milgra.com/downloads/hsme/](http://www.milgra.com/downloads/hsme/), thanks!
