### ISSUE TITLE
Option to disable menu icon

### ISSUE THREAD

**Issue by AdriaandeJongh** [milgra/highsierramediakeyenabler#49]
I have soooooo many menu icons, and with the functionality that HighSierraMediaKeyEnabler has, I really do not need to see that icon all the time.

**Comment by fabi94music** [comment]
A suggestion for a possible new icon :) @milgra 

![hsmke](https://user-images.githubusercontent.com/29753374/43038702-8790788e-8d1e-11e8-882d-4f207af6cc96.png)

**Comment by AdriaandeJongh** [comment]
Ha! I noticed I left out a crucial word in my original post; the word DON'T! I really do not need to see the icon all the time. Please allow us to hide it!

**Comment by alejandroivan** [comment]
There are excellent softwares that you can use to hide menu icons.
For example, [Vanilla](https://matthewpalmer.net/vanilla/) by Matthew Palmer.

I personally prefer [Bartender 3](https://www.macbartender.com/) by Surtees Studios, which worked better for me with a two-or-more screen setup.

**Comment by Hum4n01d** [comment]
If there isn't an icon in the menu bar nor in the dock, how would you know that the app was running/control it?

**Comment by jdanbrown** [comment]
Here's an alternative (more manual) approach I followed to avoid accumulating more menubar icons:
- https://bekirserifoglu.wordpress.com/2017/10/01/solutionworkaround-for-mac-os-high-sierra-unified-media-buttons-playpause-next-and-previous-track-problem/

**Comment by milgra** [comment]
Sorry but I don't want to make the menu inaccessibleso I won't add an icon hiding functionality. But as @alejandroivan wrote there are other tools you can use for that, Vanilla for example which has a free version.
