### ISSUE TITLE
Tidal support

### ISSUE THREAD

**Issue by raulfragoso** [milgra/highsierramediakeyenabler#5]
This is actually awesome! Thanks for doing this, I can finally have the media keys working again.
Is it possible to add support for Tidal as well?

**Comment by scporse** [comment]
+1

**Comment by milgra** [comment]
Hi, I tried to add Tidal support but Tidal doesn't have any apple script API which my app uses - so it's impossible to add Tidal at the moment :( You should try http://beardedspice.github.io , maybe it uses some different method.

**Comment by neonbaer** [comment]
Hey :)
Any news on the Tidal issue? I don't get it to work with BeardedSpice and your tool is anyway working much better.

**Comment by milgra** [comment]
Sorry, still no applescript support :(
