### ISSUE TITLE
"Open at login" state can be incorrect while running

### ISSUE THREAD

**Issue by dnicolson** [milgra/highsierramediakeyenabler#53]
If a user changes HighSierraMediaKeyEnabler in Login Items or programatically via System Events, it can become out of sync as it's only checked when the app is launched.

The fix seemed simple enough, calling `[self updateStartupItemState]` on `menuWillOpen` instead of `applicationDidFinishLaunching`. However, this only worked properly after the second time `menuWillOpen` was called. There could be an issue with [GBLaunchAtLogin](https://github.com/lmirosevic/GBLaunchAtLogin) as `[GBLaunchAtLogin isLoginItem]` returned an incorrect value the first time.

**Comment by jadchaar** [comment]
I have this issue as well. Even though the box is checked, the app does not open automatically when I restart. I have to remember to manually open it.
