### ISSUE TITLE
Incorrect Menu Bar Icon Dimensions

### ISSUE THREAD

**Issue by Hum4n01d** [milgra/highsierramediakeyenabler#56]
The icon for the app is a square (1024x1024px) but it should be a 16x22px rectangle to match the size of most other menu bar apps. I will submit a pull request when I get a chance.

**Comment by milgra** [comment]
Added, thanks very much! :)

**Comment by Hum4n01d** [comment]
This is still wrong, can you fix it please?

**Comment by Hum4n01d** [comment]
Compare:
![image](https://user-images.githubusercontent.com/17228477/59244702-72f7ae00-8bca-11e9-987d-9149ee2f45b9.png)
![image](https://user-images.githubusercontent.com/17228477/59244717-7db24300-8bca-11e9-9a1a-e445a3d5fc5e.png)
![image](https://user-images.githubusercontent.com/17228477/59244724-830f8d80-8bca-11e9-9078-f917ece5d264.png)

With:
![image](https://user-images.githubusercontent.com/17228477/59244705-75f29e80-8bca-11e9-8c33-6d3611039dec.png)
