### ISSUE TITLE
Previous Button Doesn't Restart Song

### ISSUE THREAD

**Issue by ben-kropf** [milgra/highsierramediakeyenabler#8]
I believe default MacOS behavior was to return to the beginning of the song if your press previous when you're after 4? seconds into the song. Currently, the previous button always skips to the previous song.

**Comment by mchaput** [comment]
The app should send the "back track" message instead of "previousTrack" in the AppDelegate.

**Comment by milgra** [comment]
fixed, thank you!

**Comment by ben-kropf** [comment]
Thank you!
