### ISSUE TITLE
Media key enabler doesn't work while Plex Media Player is open

### ISSUE THREAD

**Issue by scporse** [milgra/highsierramediakeyenabler#9]
As the title says, your otherwise awesome little app doesn't seem to function at all, while Plex Media Player is open. As soon as this app is closed again, however, functionality returns as if nothing had happened.

I really hope you're able to fix this somehow.

**Comment by milgra** [comment]
Sorry, it seems that Plex catches the button events exclusively while it is running and the OS doesn't delegates it to any other app and I can't do nothing about that :( You should try http://beardedspice.github.io , maybe it uses a different approach.

**Comment by scporse** [comment]
Dang it. I was afraid you might say that. Oh well - I might harass Plex
about this or I might just live with it. Thanks for checking, either way.
